# Schema for the configuration files of the cyd_functional_testing module.
cyd_functional_testing.settings:
  type: config_object
  label: 'cyd_functional_testing settings'
  mapping:
    example:
      type: string
      label: 'Example'
