name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print stuff
        run: |
          echo "text: ${{ github.event.commits[0].message }}"
          cd slskslk

      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: '8.1'
          php_extensions: gd
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install ddev.
        run: |
          curl -fsSL https://apt.fury.io/drud/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ddev.gpg > /dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/ddev.gpg] https://apt.fury.io/drud/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list
          sudo apt update && sudo apt install -y ddev

      - name: Boot dddev
        run: ddev start

      - name: Install site
        run: ddev drush si -y

      - name: Enable testing dependencies.
        run: ddev drush en cyd_functional_testing -y

      - name: Install node dependencies.
        run: yarn install --frozen-lockfile

      - name: Run tagged tests.
        if: ${{ contains(github.event.head_commit.message, '@tags=') }}
        run: |
          echo "text: ${{ github.event.head_commit.message }}"
          readarray -d "@tags=" -t strarr <<< "${{ github.event.head_commit.message }}"
          echo "tags: ${strarr[1]}"

      - name: Run other tests.
        if: ${{ !contains(github.event.head_commit.message, '@tags=') }}
        run: yarn run cypress run

      #      - name: Publish test results.
      #        uses: EnricoMi/publish-unit-test-result-action@v1
      #        if: github.actor != 'dependabot[bot]' && steps.cypress.outcome != 'success'
      #        with:
      #          files: cypress/*.png
      #          check_name: "Cypress Test Results"
      #
      #      - name: Archive test results.
      #        uses: actions/upload-artifact@v2
      #        if: steps.cypress.outcome != 'success'
      #        with:
      #          name: cypress-results
      #          path: cypress
      #          retention-days: 2

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
