name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: gd

      - name: Install cypress dependencies.
        run: yarn install --frozen-lockfile

      - name: Boot dddev
        run: ./ddev start

      - name: Install site
        run: ./ddev drush si -y

      - name: Run cypress.
        run: yarn run cy:run
